import { Injectable } from '@angular/core';
import { Observable, throwError } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import 'rxjs/add/operator/catch';

import { Book } from './book';
import { Author } from '../author/author';
import { Review } from './review';

import { environment } from '../../environments/environment';
const API_URL = environment.apiURL;
const books = '/books';
const authors = '/authors';
const reviews = '/reviews';

/**
* The service provider for everything related to books
*/
@Injectable()
export class BookService {

    /**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
    constructor(private http: HttpClient) { }

    /**
    * Retrieves the list of books in the BookStore
    * @returns The list of books
    */
    getBooks(): Observable<Book[]> {
        return this.http.get<Book[]>(API_URL + books).catch(err => this.handleError(err));
    }

    /**
    * Retrieves the information of a book in the BookStore given its id
    * @param bookId The book's id
    * @returns The book
    */
    getBook(bookId): Observable<Book> {
        return this.http.get<Book>(API_URL + books + '/' + bookId).catch(err => this.handleError(err));
    }

    /**
    * Retrieves the list of authors of a book given its id
    * @param bookId The book's id
    * @returns The list of authors of the book
    */
    getBookAuthors(bookId): Observable<Author[]> {
        return this.http.get<Author[]>(API_URL + books + '/' + bookId + authors).catch(err => this.handleError(err));
    }

    /**
    * Retrieves the reviews of a book given its id
    * @param bookId The book's id
    * @returns The list of the reviews
    */
    getReviews(bookId): Observable<Review[]> {
        return this.http.get<Review[]>(API_URL + books + '/' + bookId + reviews).catch(err => this.handleError(err));
    }

    /**
    * Creates a new book
    * @param book The new book
    * @returns The book with its new id if it was created, false if it wasn't
    */
    createBook(book): Observable<Book> {
        return this.http.post<Book>(API_URL + books, book).catch(err => this.handleError(err));
    }

    /**
    * Updates a new book
    * @param book The updated book
    * @returns The updated book
    */
    updateBook(book): Observable<Book> {
        return this.http.put<Book>(API_URL + books + '/' + book.id, book).catch(err => this.handleError(err));
    }

    /**
    * Deletes a book
    * @param bookId The book's id
    * @returns True if the book was deleted, false otherwise
    */
    deleteBook(bookId): Observable<boolean> {
        return this.http.delete<boolean>(API_URL + books + '/' + bookId).catch(err => this.handleError(err));
    }

    /**
    * Posts a review
    * @param review The review
    * @returns True if the review was posted, false otherwise
    */
    postReview(review): Observable<boolean> {
        return this.http.post<boolean>(API_URL + books + reviews, review).catch(err => this.handleError(err));
    }

    /**
    * The function which handles the errors generated by the requests
    * @param error The error which the API REST returned
    */
    private handleError(error: any) {
        return throwError(error.error.errorMessage);
    }
}
